# This script monitors multiple hosts
# when ever any host is up or down
# this script display's notification and send mail to ubuntu and cent os vertual machines

from icmplib import multiping
import time
from notification import display
import smtplib
from email.message import EmailMessage

# writing a function for mail delivery

def mail(ip, body, result):
    message = EmailMessage()
    sender= "Auto_python_code@srivatsava.com"
    reciepient = ["ubuntu@srivatsava.com","cent@srivatsava.com"]
    message['From']= sender
    message['To'] = reciepient 
    message['subject'] = "{} is {}".format(ip, result)
    message.set_content(body)
    mail_server = smtplib.SMTP("192.168.0.3")
    mail_server.login(sender,'!@Mstrong')
    mail_server.set_debuglevel(1)
    mail_server.send_message(message)
    mail_server.quit

# entering all the ip's we want to ping in to a dictionary
hosts = {"196.12.36.25":None,"196.12.36.26":None,"196.12.36.27":None,"196.12.36.28":None,"192.168.0.20": None,"192.168.0.12": None,"192.16.0.9":None}
#appending all keys to a list
ip_s = [keys for keys in hosts.keys()]

while(True):
    # to compare values in dictionary creating a list to hold current ip status
    initial_values=[x for x in hosts.values()]
    # using multiping to ping all ip's which are keys in dictionary

    Results= multiping(hosts.keys())

    # iterating each element to check which ip is UP
    # dending on ip is live or not reassaign values
 
    for result in Results:
        if not result.is_alive:
            hosts[result.address] = "DOWN"

        else:
            hosts[result.address] = "UP" 
        
    #to compare change in values
    #creating a list
    present_values=[values for values in hosts.values()]
    #iterating over a length of the list to check change in values
    for i in range(len(present_values)):
        if present_values[i] != initial_values[i]:
            x= print("{} is {}".format(ip_s[i],present_values[i]))
            display(ip_s[i],present_values[i])
            body = "Hi, \nThis is a Autogenerated mail. \n{} is {}".format(ip_s[i],present_values[i])
            mail(ip_s[i],body,present_values[i])


